version: '3.8'
services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - db
    
  backend:
      build: .
      restart: always
      ports:
      - "8000:8000"
      depends_on:
        - redis
      env_file:
        - backend/.env

  celery:
    build: .
    command: celery -A backend worker -l info
    depends_on:
      - redis
      - backend

  db:
      image: postgres:13.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - backend/.env

volumes:
  postgres_data: