# Generated by Django 4.2.11 on 2024-05-04 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('motive', models.CharField(choices=[('BRD', 'Birthday'), ('MRG', 'Marriage'), ('GFT', 'Gift')], max_length=3)),
                ('description', models.TextField()),
                ('total', models.PositiveBigIntegerField(default=None, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('end_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pay', models.PositiveIntegerField()),
                ('date_pay', models.DateTimeField()),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect', to='collect.collect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
