# Generated by Django 4.2.11 on 2024-05-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_alter_collect_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collect',
            name='name',
            field=models.CharField(max_length=240),
        ),
    ]
