# Generated by Django 4.2.11 on 2024-05-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_alter_collect_image_alter_collect_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='collect.collect'),
        ),
    ]
